# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import users_pb2 as users__pb2


class UsersInfoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUsers = channel.unary_unary(
                '/UsersInfo/GetUsers',
                request_serializer=users__pb2.UserRequest.SerializeToString,
                response_deserializer=users__pb2.UserRequest.FromString,
                )
        self.GetProducts = channel.unary_unary(
                '/UsersInfo/GetProducts',
                request_serializer=users__pb2.ProductRequest.SerializeToString,
                response_deserializer=users__pb2.ProductRequest.FromString,
                )
        self.GetVendors = channel.unary_unary(
                '/UsersInfo/GetVendors',
                request_serializer=users__pb2.VendorsRequest.SerializeToString,
                response_deserializer=users__pb2.VendorsRequest.FromString,
                )
        self.GetPayments = channel.unary_unary(
                '/UsersInfo/GetPayments',
                request_serializer=users__pb2.PaymentsRequest.SerializeToString,
                response_deserializer=users__pb2.PaymentsRequest.FromString,
                )


class UsersInfoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProducts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVendors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPayments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UsersInfoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsers,
                    request_deserializer=users__pb2.UserRequest.FromString,
                    response_serializer=users__pb2.UserRequest.SerializeToString,
            ),
            'GetProducts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProducts,
                    request_deserializer=users__pb2.ProductRequest.FromString,
                    response_serializer=users__pb2.ProductRequest.SerializeToString,
            ),
            'GetVendors': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVendors,
                    request_deserializer=users__pb2.VendorsRequest.FromString,
                    response_serializer=users__pb2.VendorsRequest.SerializeToString,
            ),
            'GetPayments': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPayments,
                    request_deserializer=users__pb2.PaymentsRequest.FromString,
                    response_serializer=users__pb2.PaymentsRequest.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'UsersInfo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UsersInfo(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UsersInfo/GetUsers',
            users__pb2.UserRequest.SerializeToString,
            users__pb2.UserRequest.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetProducts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UsersInfo/GetProducts',
            users__pb2.ProductRequest.SerializeToString,
            users__pb2.ProductRequest.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVendors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UsersInfo/GetVendors',
            users__pb2.VendorsRequest.SerializeToString,
            users__pb2.VendorsRequest.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPayments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UsersInfo/GetPayments',
            users__pb2.PaymentsRequest.SerializeToString,
            users__pb2.PaymentsRequest.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
